// Code generated by MockGen. DO NOT EDIT.
// Source: jwks/provider.go
//
// Generated by this command:
//
//	mockgen -source=jwks/provider.go -package=mocks -destination=mocks/jwks_provider_mock.go -mock_names=Provider=JwksProviderMock
//

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// JwksProviderMock is a mock of Provider interface.
type JwksProviderMock struct {
	ctrl     *gomock.Controller
	recorder *JwksProviderMockMockRecorder
	isgomock struct{}
}

// JwksProviderMockMockRecorder is the mock recorder for JwksProviderMock.
type JwksProviderMockMockRecorder struct {
	mock *JwksProviderMock
}

// NewJwksProviderMock creates a new mock instance.
func NewJwksProviderMock(ctrl *gomock.Controller) *JwksProviderMock {
	mock := &JwksProviderMock{ctrl: ctrl}
	mock.recorder = &JwksProviderMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *JwksProviderMock) EXPECT() *JwksProviderMockMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *JwksProviderMock) Key(kid string) (*rsa.PublicKey, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", kid)
	ret0, _ := ret[0].(*rsa.PublicKey)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *JwksProviderMockMockRecorder) Key(kid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*JwksProviderMock)(nil).Key), kid)
}

// Loaded mocks base method.
func (m *JwksProviderMock) Loaded() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Loaded")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Loaded indicates an expected call of Loaded.
func (mr *JwksProviderMockMockRecorder) Loaded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Loaded", reflect.TypeOf((*JwksProviderMock)(nil).Loaded))
}
