// Code generated by MockGen. DO NOT EDIT.
// Source: service/api/refresh/coordinator.go
//
// Generated by this command:
//
//	mockgen -source=service/api/refresh/coordinator.go -package=mocks -destination=mocks/refresh_coordinator_mock.go -mock_names=Coordinator=RefreshCoordinatorMock
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cookie "github.com/cash-track/gateway/headers/cookie"
	gomock "go.uber.org/mock/gomock"
)

// RefreshCoordinatorMock is a mock of Coordinator interface.
type RefreshCoordinatorMock struct {
	ctrl     *gomock.Controller
	recorder *RefreshCoordinatorMockMockRecorder
	isgomock struct{}
}

// RefreshCoordinatorMockMockRecorder is the mock recorder for RefreshCoordinatorMock.
type RefreshCoordinatorMockMockRecorder struct {
	mock *RefreshCoordinatorMock
}

// NewRefreshCoordinatorMock creates a new mock instance.
func NewRefreshCoordinatorMock(ctrl *gomock.Controller) *RefreshCoordinatorMock {
	mock := &RefreshCoordinatorMock{ctrl: ctrl}
	mock.recorder = &RefreshCoordinatorMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RefreshCoordinatorMock) EXPECT() *RefreshCoordinatorMockMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *RefreshCoordinatorMock) Do(ctx context.Context, key string, refresh func(context.Context) (cookie.Auth, error)) (cookie.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, key, refresh)
	ret0, _ := ret[0].(cookie.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *RefreshCoordinatorMockMockRecorder) Do(ctx, key, refresh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*RefreshCoordinatorMock)(nil).Do), ctx, key, refresh)
}
